create extension if not exists pgcrypto;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  legal_name text not null,
  trade_name text not null,
  document text,
  logo_url text,
  phone text,
  whatsapp text,
  email text,
  address jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text,
  avatar_url text,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.company_members (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'vendedor',
  permissions jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(company_id, user_id)
);

create or replace function public.my_company_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select company_id from public.company_members
  where user_id = auth.uid() and active = true
  order by created_at asc limit 1;
$$;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  kind text not null default 'pessoa_fisica',
  name text not null,
  legal_name text,
  document text,
  phone text,
  whatsapp text,
  email text,
  address jsonb not null default '{}'::jsonb,
  notes text,
  status text not null default 'ativo',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  source text not null default 'outros',
  desired_product text,
  location text,
  measurements jsonb not null default '{}'::jsonb,
  estimated_value numeric(12,2) not null default 0,
  owner_id uuid references auth.users(id),
  stage text not null default 'novo_lead',
  probability numeric(5,2) not null default 0,
  loss_reason text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  number bigint generated by default as identity,
  product jsonb not null default '{}'::jsonb,
  dimensions jsonb not null default '{}'::jsonb,
  costs jsonb not null default '{}'::jsonb,
  margin_percent numeric(7,2) not null default 0,
  discount numeric(12,2) not null default 0,
  suggested_price numeric(12,2) not null default 0,
  status text not null default 'rascunho',
  valid_until date,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.materials (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  category text,
  unit text not null default 'unidade',
  sku text,
  supplier text,
  cost numeric(12,2) not null default 0,
  stock numeric(12,3) not null default 0,
  minimum_stock numeric(12,3) not null default 0,
  maximum_stock numeric(12,3),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.production_orders (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  quote_id uuid references public.quotes(id) on delete set null,
  product jsonb not null default '{}'::jsonb,
  assigned_to uuid references auth.users(id),
  due_date date,
  priority text not null default 'normal',
  status text not null default 'aguardando_producao',
  bom jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.installations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  production_order_id uuid references public.production_orders(id) on delete set null,
  scheduled_at timestamptz,
  address jsonb not null default '{}'::jsonb,
  team jsonb not null default '[]'::jsonb,
  materials jsonb not null default '[]'::jsonb,
  tools jsonb not null default '[]'::jsonb,
  notes text,
  media jsonb not null default '[]'::jsonb,
  status text not null default 'agendada',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sync_operations (
  id uuid primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pendente',
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  synced_at timestamptz
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid references auth.users(id),
  action text not null,
  entity text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do update set full_name = excluded.full_name;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.company_members enable row level security;
alter table public.customers enable row level security;
alter table public.leads enable row level security;
alter table public.quotes enable row level security;
alter table public.materials enable row level security;
alter table public.production_orders enable row level security;
alter table public.installations enable row level security;
alter table public.sync_operations enable row level security;
alter table public.audit_logs enable row level security;

create policy "members can view company" on public.companies for select using (id = public.my_company_id());
create policy "users can view own profile" on public.profiles for select using (id = auth.uid());
create policy "members can view memberships" on public.company_members for select using (company_id = public.my_company_id());

create policy "members manage customers" on public.customers for all using (company_id = public.my_company_id()) with check (company_id = public.my_company_id());
create policy "members manage leads" on public.leads for all using (company_id = public.my_company_id()) with check (company_id = public.my_company_id());
create policy "members manage quotes" on public.quotes for all using (company_id = public.my_company_id()) with check (company_id = public.my_company_id());
create policy "members manage materials" on public.materials for all using (company_id = public.my_company_id()) with check (company_id = public.my_company_id());
create policy "members manage production" on public.production_orders for all using (company_id = public.my_company_id()) with check (company_id = public.my_company_id());
create policy "members manage installations" on public.installations for all using (company_id = public.my_company_id()) with check (company_id = public.my_company_id());
create policy "members manage sync operations" on public.sync_operations for all using (company_id = public.my_company_id() and user_id = auth.uid()) with check (company_id = public.my_company_id() and user_id = auth.uid());
create policy "members can view audit" on public.audit_logs for select using (company_id = public.my_company_id());
create policy "members can write audit" on public.audit_logs for insert with check (company_id = public.my_company_id() and user_id = auth.uid());

create index if not exists customers_company_idx on public.customers(company_id, created_at desc);
create index if not exists leads_company_stage_idx on public.leads(company_id, stage, created_at desc);
create index if not exists quotes_company_status_idx on public.quotes(company_id, status, created_at desc);
create index if not exists materials_company_stock_idx on public.materials(company_id, stock, minimum_stock);
create index if not exists installations_company_date_idx on public.installations(company_id, scheduled_at);
create index if not exists sync_operations_user_status_idx on public.sync_operations(user_id, status, created_at);
